/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Aditio
 */
public class LoginForm extends javax.swing.JFrame {
    // deklarasi
    Connection con;
    Statement state;
    ResultSet rs;
    String sql;

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        //pemanggilan fungsi koneksi database yang sudah kita buat pada class koneksi.java
        DBConnection DB = new DBConnection();
        DB.config();
        con = DB.con;
        state = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelKiri = new javax.swing.JPanel();
        LogoApp = new javax.swing.JLabel();
        panelKanan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txt_Username = new javax.swing.JTextField();
        pass_LoginPassword = new javax.swing.JPasswordField();
        ShowPassword = new javax.swing.JCheckBox();
        btn_Login = new javax.swing.JLabel();
        LoginFrame = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelKiri.setBackground(new java.awt.Color(15, 20, 15));
        panelKiri.setPreferredSize(new java.awt.Dimension(500, 600));
        panelKiri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AppLogoFull.png"))); // NOI18N
        panelKiri.add(LogoApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 155, -1, 278));

        getContentPane().add(panelKiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelKanan.setBackground(new java.awt.Color(0, 0, 0));
        panelKanan.setPreferredSize(new java.awt.Dimension(500, 600));
        panelKanan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 45, 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(410, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Username.setBackground(new java.awt.Color(20, 45, 20));
        txt_Username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_Username.setForeground(new java.awt.Color(255, 255, 255));
        txt_Username.setBorder(null);
        txt_Username.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_Username.setOpaque(false);
        txt_Username.setScrollOffset(1);
        txt_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 185, 260, 40));

        pass_LoginPassword.setBackground(new java.awt.Color(20, 45, 20));
        pass_LoginPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pass_LoginPassword.setForeground(new java.awt.Color(255, 255, 255));
        pass_LoginPassword.setBorder(null);
        pass_LoginPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        pass_LoginPassword.setOpaque(false);
        pass_LoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_LoginPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(pass_LoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 292, 260, 40));

        ShowPassword.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        ShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        ShowPassword.setText("show password");
        ShowPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(ShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 338, -1, -1));

        btn_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_Login.png"))); // NOI18N
        btn_Login.setPreferredSize(new java.awt.Dimension(142, 52));
        btn_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LoginMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 393, -1, -1));

        LoginFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LoginFrame.png"))); // NOI18N
        jPanel1.add(LoginFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 55, -1, -1));

        panelKanan.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 70, -1, -1));

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_close_LoginForm_putih.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        panelKanan.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 12, -1, -1));

        getContentPane().add(panelKanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordActionPerformed
        // TODO add your handling code here:
        if(ShowPassword.isSelected())
        {
            pass_LoginPassword.setEchoChar((char)0);
        }
        else
        {
            pass_LoginPassword.setEchoChar('*');
        }
        
    }//GEN-LAST:event_ShowPasswordActionPerformed

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i+"";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            }
            catch (Exception e){
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void txt_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsernameActionPerformed

    private void pass_LoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_LoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_LoginPasswordActionPerformed

    private void btn_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LoginMouseClicked
        // TODO add your handling code here:
        try {
            sql = "SELECT * FROM tb_user WHERE username='"+txt_Username.getText()+"' AND password='"+pass_LoginPassword.getText()+"'";
            rs = state.executeQuery(sql);
            if(rs.next()){
                if(txt_Username.getText().equals(rs.getString("username")) && pass_LoginPassword.getText().equals(rs.getString("password"))){
                    javax.swing.JOptionPane.showMessageDialog(null,"Login Berhasil.");
                    this.dispose();
                    MainApp form = new MainApp();
                    form.setLocationRelativeTo(null);
                    form.setVisible(true);
                }
            }
            else if(txt_Username.getText().equals("") && pass_LoginPassword.getText().equals("")){
                    javax.swing.JOptionPane.showMessageDialog(null,"Anda belum mengisi Username & Password.");
                }
            else if(txt_Username.getText().equals("")){
                    javax.swing.JOptionPane.showMessageDialog(null,"Anda belum mengisi Username.");
                }
            else if(pass_LoginPassword.getText().equals("")){
                    javax.swing.JOptionPane.showMessageDialog(null,"Anda belum mengisi Password.");
                }
            else {
                    javax.swing.JOptionPane.showMessageDialog(null,"Username/Password salah.");
                    txt_Username.setText("");
                    pass_LoginPassword.setText("");
                    txt_Username.requestFocus();
                }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }      
    }//GEN-LAST:event_btn_LoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginFrame;
    private javax.swing.JLabel LogoApp;
    private javax.swing.JCheckBox ShowPassword;
    private javax.swing.JLabel btn_Login;
    private javax.swing.JLabel btn_close;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelKanan;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JPasswordField pass_LoginPassword;
    private javax.swing.JTextField txt_Username;
    // End of variables declaration//GEN-END:variables
}
